<?php

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Render\RendererInterface;
use Drupal\taxonomy\Entity\Term;

function md_carousel_theme($existing, $type, $theme, $path)
{
  return [
    'home_slide' => [
      'variables' => [
        'slide' => NULL
      ],
    ],
    'home_axis' => [
      'variables' => [
        'axis' => NULL
      ],
    ],
    'home_axis_interne' => [
      'variables' => [
        'axis' => NULL
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter() for node_form.
 */
function md_carousel_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

 
  if (($form_id == 'node_announcement_form') || ($form_id == 'node_announcement_edit_form')) {
      // Adding AJAX properties to 'field_status'.
       
      $form['field_status']['widget']['#ajax'] = [
          'callback' => 'md_carousel_status_ajax_callback',
          'wrapper' => 'edit-field-number-post-wrapper',
          'event' => 'change',
          'progress' => [
              'type' => 'throbber',
              'message' => t('Updating...'),
          ],
      ];
      
      // Wrapper for 'field_number_post' to be updated by AJAX.

      $form['field_number_post']['#prefix'] = '<div id="edit-field-number-post-wrapper">';
      $form['field_number_post']['#suffix'] = '</div>';
      
  }
}

function md_carousel_status_ajax_callback(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $renderer = \Drupal::service('renderer');
  $response = new AjaxResponse();

  $node = $form_state->getFormObject()->getEntity();

  // Check if the field_status field is set and not empty.
  if ($node->hasField('field_status') && !$node->get('field_status')->isEmpty()) {
    $user_input = $form_state->getUserInput();
    $selected_value = $user_input['field_status'];

      // Update the 'field_number_post' access and default value based on 'field_status'.
      if ($selected_value === '35') {
          $form['field_number_post']['#access'] = true;

      } else {
          $form['field_number_post']['#access'] = false;

      }

      // Re-render the 'field_number_post' element.
      $number_post_html = $renderer->renderRoot($form['field_number_post']);
      $response->addCommand(new HtmlCommand('#edit-field-number-post-wrapper', $number_post_html));
  }

  return $response;
}
