<?php

function md_carousel_theme($existing, $type, $theme, $path)
{
  return [
    'home_slide' => [
      'variables' => [
        'slide' => NULL
      ],
    ],
    'home_axis' => [
      'variables' => [
        'axis' => NULL
      ],
    ],
    'home_axis_interne' => [
      'variables' => [
        'axis' => NULL
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter() for node_form.
 */
function md_carousel_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  \Drupal::logger('md_carousel')->notice('Form alter hook called for form ID: @form_id', ['@form_id' => $form_id]);

  if ($form_state->getFormObject()->getEntity()->getType() == 'announcement') {
    $form['field_status']['#ajax'] = [
      'callback' => 'md_carousel_status_ajax_callback',
      'wrapper' => 'field-number-post-wrapper',
      'event' => 'change',
    ];

    $form['field_number_post']['#prefix'] = '<div id="field-number-post-wrapper">';
    $form['field_number_post']['#suffix'] = '</div>';

    _md_carousel_toggle_field_visibility($form, $form_state);
  }
}

function _md_carousel_toggle_field_visibility(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $status_value = $form_state->getFormObject()->getEntity()->get('field_status')->value;
  \Drupal::logger('md_carousel')->notice('Toggle visibility function called. Status: @status', ['@status' => $status_value]);

  $form['field_number_post']['#access'] = ($status_value === 'Ouvert');
}

function md_carousel_status_ajax_callback(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  \Drupal::logger('md_carousel')->notice('AJAX callback called.');

  _md_carousel_toggle_field_visibility($form, $form_state);

  return $form['field_number_post'];
}
